name = "ThreadLockCaches"
uuid = "52ce2674-c759-4151-b0e5-31e05c978375"
authors = ["Moelf <proton@jling.dev> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"

[targets]
test = ["Test", "LRUCache"]
